/**
 * Core domain types for the Stake application
 */

export interface User {
  id: string;
  username: string;
  email: string;
  displayName: string;
  avatar?: string;
  bio?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Circle {
  id: string;
  name: string;
  description?: string;
  imageUrl?: string;
  members: User[];
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface BetOption {
  id: string;
  label: string;
  odds?: number;
}

export interface Bet {
  id: string;
  title: string;
  description?: string;
  createdBy: string;
  circleId?: string;
  options: BetOption[];
  status: 'OPEN' | 'LOCKED' | 'RESOLVED';
  deadline: string; // ISO datetime string
  stakeAmount?: number;
  stakeTemplate?: StakeTemplate;
  proofRequirement: 'NONE' | 'PHOTO' | 'VIDEO';
  privacy: 'FRIENDS_PUBLIC' | 'CIRCLE_PRIVATE';
  participants?: BetParticipant[];
  resolvedAt?: string;
  resolutionDetails?: {
    winningOptionId: string;
    winnerIds: string[];
  };
  createdAt: string;
  updatedAt: string;
}

export interface BetParticipant {
  id: string;
  betId: string;
  userId: string;
  user?: User;
  selectedOptionId: string;
  selectedOption?: BetOption;
  amount?: number;
  status?: 'pending' | 'won' | 'lost';
  stakeInstance?: StakeInstance; // Only for losers who need to complete stakes
  createdAt: string;
}

export interface StakeTemplate {
  id: string;
  name: string;
  description?: string;
  icon?: string;
  proofType: string;
  createdAt: string;
}

export interface ProofUpload {
  id: string;
  betId: string;
  stakeInstanceId: string;
  userId: string;
  proofUrl: string; // File URL (image or video)
  proofType: 'PHOTO' | 'VIDEO';
  uploadedAt: string;
}

export interface IdentityBadge {
  id: string;
  userId: string;
  badgeName: string;
  issuer: string;
  verifiedAt: string;
}

export interface StakeInstance {
  id: string;
  betId: string;
  userId: string;
  templateId?: string;
  proofRequirement: 'NONE' | 'PHOTO' | 'VIDEO';
  status: 'pending' | 'completed' | 'rejected';
  proofUpload?: ProofUpload;
  createdAt: string;
  completedAt?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    status: number;
    message: string;
    details?: unknown;
  };
}

export interface AuthToken {
  accessToken: string;
  refreshToken?: string;
  expiresIn?: number;
}

export interface AuthState {
  user: User | null;
  token: string | null;
  isLoading: boolean;
  error: string | null;
}

export interface FriendRequest {
  id: string;
  senderId: string;
  sender?: User;
  recipientId: string;
  recipient?: User;
  status: 'pending' | 'accepted' | 'declined';
  createdAt: string;
  respondedAt?: string;
}

export interface Friendship {
  id: string;
  userId: string;
  user?: User;
  friendId: string;
  friend?: User;
  createdAt: string;
}

export interface Follow {
  id: string;
  followerId: string;
  follower?: User;
  followingId: string;
  following?: User;
  createdAt: string;
}

/**
 * Identity badge with 4 pillar scores
 * Generated by Gemini based on user activity
 */
export interface IdentityBadgeDetail {
  id: string;
  userId: string;
  title: string;
  description: string;
  pillars: {
    express: number; // 0-100: Self-expression & Communication
    protect: number; // 0-100: Protection & Accountability
    create: number; // 0-100: Creation & Innovation
    evolve: number; // 0-100: Evolution & Growth
  };
  generatedAt: string;
  updatedAt: string;
}

export interface UserStats {
  totalBets: number;
  wonBets: number;
  lostBets: number;
  friends: number;
  following: number;
  createdAt: string;
}
